### PR TITLE
Add outdated dependency info message

### PR DESCRIPTION
**Pull request by sigseg5**
Changes:
* Add outdated dependency info message;
* Apply npm format to all files;
* Bump project dependencies;
* Add build instructions

### CODE REVIEW

**Comment by Twixes** [comment]
Hey @sigseg5! Thanks for the initiative, love to see it. Unfortunately though, this feature is not really valid. The problem is that it's rarely possible to figure out what version of a package is actually installed based on `requirements.txt`, because often version ranges are used. For instance here:

Screenshot 2023-07-25 at 01 48 47

This specifier does actually point to the latest version of the package, although still it is not possible to say that the latest one is indeed installed, because if a lockfile is generated with e.g. `pip-compile`, another package may require a different version range, resulting in an intersection of ranges.

This is not really solvable, which is why the PyPI Assistant CodeLenses only loosely provide the latest version, and don't authoritatively say that the specifier points to an outdated version.

**Comment by Twixes** [comment]
I definitely appreciate the addition of documentation, happy to accept as a PR of its own. Closing the "installed version" change per above.

**Comment by sigseg5** [comment]
Thx for answer @Twixes!
So, what do you think about this solution, you could show the update availability message only for cases with '=='? For me such an option would be quite convenient, and there would be no package compatibility issues due to the use of ranges. Here is a sample [code](https://github.com/sigseg5/pypi-assistant/blob/0fa754aaee191b8f0878e1075a5f4dc9f3ad6149/src/extension.ts#L111) (also see `satisfies ` function)

**Comment by Twixes** [comment]
Hmm, well, yes, but even in that case things are not so simple, because the `package==1.2.*` form is also commonly used. That means support for outdated package highlighting would be very very limited. I believe that the current experience of just visually noticing a discrepancy by seeing "Latest version: ..." works very well.

**Pull request closed without merging**
